default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
  database: <%= Rails.configuration.db['database'] %>
  username: <%= Rails.configuration.db['username'] %>
  password: <%= Rails.configuration.db['password'] %>
  host: <%= Rails.configuration.db['host'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
